In [ ]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('dataset.csv')

In [4]:
df.head()  #1 means real news 0 means fake news

                                                text  label
0  Gere faults Trump for blurring meaning of 'ref...      1
1  German parties start to find common ground in ...      1
2  Senate Democratic leader says Attorney General...      1
3  Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4   Trump Threw Mar-A-Lago Fundraiser For Woman A...      0

In [5]:
df.shape

(45757, 2)

In [6]:
df['text'][1]

'German parties start to find common ground in coalition talks BERLIN (Reuters) - Parties seeking to form Germany s next government found common ground in areas of social policy and digital infrastructure on Monday, but remain far apart on issues that provoked stormy clashes last week. Talks between conservatives, Greens and Free Democrats (FDP) resumed on Monday after Chancellor Angela Merkel convened a weekend meeting to clear the air between ideologically diverse parties forced by electoral arithmetic into awkward partnership.  The weekend pause for thought did us good,  said Andreas Scheuer, a leader in the conservative Christian Social Union (CSU), the Bavarian sister party to Merkel s Christian Democrats (CDU). Other party leaders agreed. But Monday s talks, on education, digitalization, pensions and labor issues, as well as domestic security, were always expected to be less contentious than the immigration, fiscal and climate policies that divided them last week. One sign of the division came in an interview Merkel ally Peter Altmaier gave to the newspaper Die Zeit, where he shot down media reports about a reshuffling of ministerial portfolios. Der Spiegel magazine reported the FDP might head a weakened finance ministry, with key European affairs functions hived off to another ministry.  The finance ministry is a strong ministry and should remain so in future,  Altmaier told Die Zeit. Altmaier runs Merkel s office and has been acting finance minister since Wolfgang Schaeuble s move agreed last month to leave the post and become president of parliament . Negotiators emerged on Monday with a document spelling out areas where they had reached agreement, including commitments to universal gigabit-speed internet by 2025, and spending 3.5 percent of economic output on research and development. After discussions that ran late into the evening, they also signed up to Merkel s election campaign pledge of achieving full employment, without giving a specific target date. Merkel, whose conservatives came first but lost seats in the Sept. 24 national elections must forge a so-called  Jamaica  coalition - named because the three camps  colors match that country s flag - that is untested at national level. Three more rounds of more detailed exploratory talks are planned for this week and four for next. If successful, the parties can then begin formal coalition talks. '

In [7]:
df.isnull().sum()

text     0
label    0
dtype: int64

In [8]:
df['text'].duplicated().sum()

0

In [ ]:
df['label'].value_counts()

label
1    22900
0    22857
Name: count, dtype: int64

In [10]:
df.head(15)

                                                 text  label
0   Gere faults Trump for blurring meaning of 'ref...      1
1   German parties start to find common ground in ...      1
2   Senate Democratic leader says Attorney General...      1
3   Tennis: Kyrgios fined $10,000 for Shanghai wal...      1
4    Trump Threw Mar-A-Lago Fundraiser For Woman A...      0
5    President Curtsy Delivers A Really Sick Burn ...      0
6   NSA risks talent exodus amid morale slump, Tru...      1
7    Trump Completely COLLAPSING In Most Important...      0
8   John Kerry commits more U.S. military aid for ...      1
9   BOOM! Hey Democrats….Why The Violent Riots? YO...      0
10  WHOA! MICHAEL MOORE Says TRUMP Is Only Hope To...      0
11  SPOT ON! MARK STEYN Delivers A Dire Warning To...      0
12  Hundreds rally in France to protest sexual har...      1
13   WATCH: Nicolle Wallace Takes Trump To The Woo...      0
14  Suppressing free press is 'how dictators get s...      1

# preprocessing

In [11]:
df['text'] = df['text'].str.lower()

In [12]:
df.head()

                                                text  label
0  gere faults trump for blurring meaning of 'ref...      1
1  german parties start to find common ground in ...      1
2  senate democratic leader says attorney general...      1
3  tennis: kyrgios fined $10,000 for shanghai wal...      1
4   trump threw mar-a-lago fundraiser for woman a...      0

In [13]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    return ' '.join(
        word for word in text.split()
        if word.lower() not in stop_words
    )

In [14]:
df['text'] = df['text'].apply(remove_stopwords)

In [15]:
df.head()

                                                text  label
0  gere faults trump blurring meaning 'refugee' '...      1
1  german parties start find common ground coalit...      1
2  senate democratic leader says attorney general...      1
3  tennis: kyrgios fined $10,000 shanghai walk te...      1
4  trump threw mar-a-lago fundraiser woman center...      0

In [16]:
df['text'][1]

'german parties start find common ground coalition talks berlin (reuters) - parties seeking form germany next government found common ground areas social policy digital infrastructure monday, remain far apart issues provoked stormy clashes last week. talks conservatives, greens free democrats (fdp) resumed monday chancellor angela merkel convened weekend meeting clear air ideologically diverse parties forced electoral arithmetic awkward partnership. weekend pause thought us good, said andreas scheuer, leader conservative christian social union (csu), bavarian sister party merkel christian democrats (cdu). party leaders agreed. monday talks, education, digitalization, pensions labor issues, well domestic security, always expected less contentious immigration, fiscal climate policies divided last week. one sign division came interview merkel ally peter altmaier gave newspaper die zeit, shot media reports reshuffling ministerial portfolios. der spiegel magazine reported fdp might head weakened finance ministry, key european affairs functions hived another ministry. finance ministry strong ministry remain future, altmaier told die zeit. altmaier runs merkel office acting finance minister since wolfgang schaeuble move agreed last month leave post become president parliament . negotiators emerged monday document spelling areas reached agreement, including commitments universal gigabit-speed internet 2025, spending 3.5 percent economic output research development. discussions ran late evening, also signed merkel election campaign pledge achieving full employment, without giving specific target date. merkel, whose conservatives came first lost seats sept. 24 national elections must forge so-called jamaica coalition - named three camps colors match country flag - untested national level. three rounds detailed exploratory talks planned week four next. successful, parties begin formal coalition talks.'

In [17]:
import string

df['punct_count'] = df['text'].apply(
    lambda x: sum(1 for char in x if char in string.punctuation)
)

df.groupby('label')['punct_count'].describe()

         count       mean        std  min   25%   50%   75%     max
label
0      22857.0  51.609398  79.653637  0.0  16.0  44.0  66.0  7295.0
1      22900.0  55.443930  44.897107  1.0  23.0  47.0  73.0  1144.0

In [18]:
df[df['label']==0].sort_values('punct_count', ascending=False)[['text','punct_count']].head(10)

                                                    text  punct_count
32793  fed republicans threaten third party option tr...         7295
36842  stephen colbert gets donald rumsfeld admit ira...         4836
32225  god bible architect great pyramid - unlocking ...         1564
26592  state’s economy rank? washington dc’s ranking ...          943
16167  obama commutes 61 prisoners’ sentences…here’s ...          920
43443  wow! america attack 187 organizations directly...          789
21642  anti-american george soros locks arms nfl trum...          765
16923  durham bulls 2017 - part 2 - pitchers durham b...          754
20     we’ve got list bill hillary clinton’s speeches...          724
17544  fundamental constitutional rights negated real...          714

In [19]:
df['text'][32793]

"fed republicans threaten third party option trump nominee saying long time republican party verge splitting right. sort of. always assumed establishment would control party iron fist tea party white supremacists would abandon gop form white power party. rise donald trump, looks like establishment going abandon party run candidate raving sociopath:spurred donald j. trump mounting victories, small influential growing group conservative leaders calling third-party option spare voters wrenching general election choice republican consider completely unacceptable hillary clinton.while gained intense popularity right, mr. trump alienated key blocs republican coalition slash-and-burn campaign. many, initial refusal last weekend disavow endorsement david duke, white supremacist, breaking point. breaking point ass. problem conservative leaders trump racism overt nature it. republicans relied white resentment 50 years win elections, keep concealed lest get publicly torn apart party old white racists. corporate media happy promote fiction trump making impossible. real problem republicans trump. that, uncontrollable buffoon, unlike george w. bush perfect puppet 1% manipulate.but think moment: conservative movement appalled front-runner going deliberately sabotage party keep trump office. lunatics officially taken control asylum.william kristol, editor conservative weekly standard magazine, said would work actively put forward independent republican ticket mr. trump nominee, floated mr. sasse recruit. ticket would simply one-time, emergency adjustment unfortunate circumstance (if happens) trump nomination, mr. kristol wrote email. would support republicans running congress offices, would allow voters correct temporary mistake (if make it) nominating trump. kristol many things, stupid one them. knows full well running another conservative would hand election democratic nominee silver platter. fact presumptive nominee hillary clinton, hated woman conservative world, even seem factor.max boot, foreign policy adviser senator marco rubio florida, said efforts block mr. trump fell short, would vote republican nominee first time life. would sooner vote josef stalin would vote donald trump, said mr. boot, expressed optimism mr. trump could still defeated. added: way hell would ever vote him. would far readily support hillary clinton, bloomberg ran. wonder frothing masses hillary clinton hating liberals take kind news? one precious narratives trump easily beat clinton republicans hate anything therefor allowed nominee. much myth. also, true first place:defections scale could prove lethal mr. trump. already trails mrs. clinton general election polls, polling already shows possibility mass desertions party. cnn/opinion research corporation survey week found 48 percent republicans already back mr. trump said would probably definitely support november.when asked possibility revolt not-completely-insane wing party, trump replied typical 4th grade eloquence, lose everything, would work loser. oddly, third party would actually hurt democrats general election. would deliver us white house ease, would bring voters would otherwise stayed home disgust. would almost certainly vote ticket, making senate, house local elections harder win democratic candidates. hand, would represent schism republican party might able recover hard know cheering plan not.featured image via cagle.com // < ![cdata[ // < ![cdata[ // < ![cdata[ // < ![cdata[ // < ![cdata[ (function(){var h=this,aa=function(a){var b=typeof a;if(&quot;object&quot;==b)if(a){if(a instanceof array)return&quot;array&quot;;if(a instanceof object)return b;var c=object.prototype.tostring.call(a);if(&quot;[object window]&quot;==c)return&quot;object&quot;;if(&quot;[object array]&quot;==c||&quot;number&quot;==typeof a.length&amp;&amp;&quot;undefined&quot;!=typeof a.splice&amp;&amp;&quot;undefined&quot;!=typeof a.propertyisenumerable&amp;&amp;!a.propertyisenumerable(&quot;splice&quot;))return&quot;array&quot;;if(&quot;[object function]&quot;==c||&quot;undefined&quot;!=typeof a.call&amp;&amp;&quot;undefined&quot;!=typeof a.propertyisenumerable&amp;&amp;!a.propertyisenumerable(&quot;call&quot;))return&quot;function&quot;}else return&quot;null&quot;;else if(&quot;function&quot;==b&amp;&amp;&quot;undefined&quot;==typeof a.call)return&quot;object&quot;;return b},k=function(a){return&quot;string&quot;==typeof a},ba=function(a,b){var c=array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},m=date.now||function(){return+new date},n=function(a,b){var c=a.split(&quot;.&quot;),d=h;c[0]in d||!d.execscript||d.execscript(&quot;var &quot;+c[0]);for(var e;c.length&amp;&amp;(e=c.shift());)c.length||void 0===b?d=d[e]?d[e]:d[e]={}:d[e]=b};var ca=function(a,b,c,d,e){if(e)c=a+(&quot;&amp;&quot;+b+&quot;=&quot;+c);else{var f=&quot;&amp;&quot;+b+&quot;=&quot;,g=a.indexof(f);0>g?c=a+f+c:(g+=f.length,f=a.indexof(&quot;&amp;&quot;,g),c=0< =f?a.substring(0,g)+c+a.substring(f):a.substring(0,g)+c)}return 2e3<c.length?void 0!==d?ca(a,b,d,void 0,e):a:c};var da=function(){var a=/[&amp;\\?]exk=([^&amp; ]+)/.exec(p.location.href);return a&amp;&amp;2==a.length?a[1]:null};var q=function(a,b){this.width=a;this.height=b};q.prototype.clone=function(){return new q(this.width,this.height)};q.prototype.ceil=function(){this.width=math.ceil(this.width);this.height=math.ceil(this.height);return this};q.prototype.floor=function(){this.width=math.floor(this.width);this.height=math.floor(this.height);return this};q.prototype.round=function(){this.width=math.round(this.width);this.height=math.round(this.height);return this};q.prototype.scale=function(a,b){this.width*=a;this.height*=&quot;number&quot;==typeof b?b:a;return this};var ea=function(a,b){for(var c a)object.prototype.hasownproperty.call(a,c)&amp;&amp;b.call(void 0,a[c],c,a)},ga=function(){var a=fa;if(!a)return&quot;&quot;;var b=/.*[&amp;#?]google_debug(=[^&amp;]*)?(&amp;.*)?$/;try{var c=b.exec(decodeuricomponent(a));if(c)return c[1]&amp;&amp;1<c[1].length?c[1].substring(1):&quot;true&quot;}catch(d){}return&quot;&quot;};var ha=function(a,b,c,d){a.addeventlistener?a.addeventlistener(b,c,d||!1):a.attachevent&amp;&amp;a.attachevent(&quot;on&quot;+b,c)};var ia=function(a,b){var c=[];ea(a,function(a,e){var f=null,g=typeof a;if((&quot;object&quot;==g&amp;&amp;null!=a||&quot;function&quot;==g)&amp;&amp;2>b)f=ia(a,b+1);else if(0===a||a)f=string(a);f&amp;&amp;c.push(e+&quot;=&quot;+encodeuricomponent(f))});return c.join(&quot;&amp;&quot;)},r=function(a,b,c){a.google_image_requests||(a.google_image_requests=[]);var d=a.document.createelement(&quot;img&quot;);if(c){var e=function(a){c(a);a=e;d.removeeventlistener?d.removeeventlistener(&quot;load&quot;,a,!1):d.detachevent&amp;&amp;d.detachevent(&quot;onload&quot;,a);a=e;d.removeeventlistener?d.removeeventlistener(&quot;error&quot;,a,!1):d.detachevent&amp;&amp;d.detachevent(&quot;onerror&quot;,a)};ha(d,&quot;load&quot;,e);ha(d,&quot;error&quot;,e)}d.src=b;a.google_image_requests.push(d)};var ja=function(a,b,c){this.v=a;this.u=b;this.c=c;this.f=null;this.s=this.g;this.a=!1},ka=function(a,b,c){this.message=a;this.filename=b||&quot;&quot;;this.linenumber=c||-1},ma=function(a,b,c){var d;try{d=c()}catch(g){var e=a.c;try{var f=la(g),e=a.s.call(a,b,f,void 0,void 0)}catch(l){a.g(&quot;par&quot;,l)}if(!e)throw g;}finally{}return d},t=function(a,b){var c=na;return function(){var d=arguments;return ma(c,a,function(){return b.apply(void 0,d)})}};ja.prototype.g=function(a,b,c,d,e){var f={};f.context=a;b instanceof ka||(b=la(b));f.msg=b.message.substring(0,512);b.filename&amp;&amp;(f.file=b.filename);0<b .linenumber&amp;&amp;(f.line=b.linenumber.tostring());a=h.document;f.url=a.url.substring(0,512);f.ref=a.referrer.substring(0,512);if(this.f)try{this.f(f)}catch(l){}if(d)try{d(f)}catch(l){}d=this.v;try{if((this.a?d.w:math.random())<(c||d.o)){var g=d.m+(e||this.u)+(&quot;&amp;&quot;+ia(f,1)),g=g.substring(0,2e3);r(h,g)}}catch(l){}return this.c};var la=function(a){var b=a.tostring();a.name&amp;&amp;-1==b.indexof(a.name)&amp;&amp;(b+=&quot;: &quot;+a.name);a.message&amp;&amp;-1==b.indexof(a.message)&amp;&amp;(b+=&quot;: &quot;+a.message);if(a.stack){var c=a.stack,d=b;try{-1==c.indexof(d)&amp;&amp;(c=d+&quot;\\n&quot;+c);for(var e;c!=e;)e=c,c=c.replace(/((https?:\\/..*\\/)[^\\/:]*:\\d+(?:.|\\n)*)\\2/,&quot;$1&quot;);b=c.replace(/\\n */g,&quot;\\n&quot;)}catch(f){b=d}}return new ka(b,a.filename,a.linenumber)};var oa=string.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\\s\\u00a0]+|[\\s\\u00a0]+$/g,&quot;&quot;)},pa=function(a,b){return a<b?-1:a>b?1:0};var qa=array.prototype.indexof?function(a,b,c){return array.prototype.indexof.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?math.max(0,a.length+c):c;if(k(a))return k(b)&amp;&amp;1==b.length?a.indexof(b,c):-1;for(;c<a .length;c++)if(c a&amp;&amp;a[c]===b)return c;return-1},ra=array.prototype.map?function(a,b,c){return array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=array(d),f=k(a)?a.split(&quot;&quot;):a,g=0;g<d;g++)g f&amp;&amp;(e[g]=b.call(c,f[g],g,a));return e};var sa=function(a,b){for(var c a)b.call(void 0,a[c],c,a)};var v;a:{var ta=h.navigator;if(ta){var ua=ta.useragent;if(ua){v=ua;break a}}v=&quot;&quot;}var w=function(a){return-1!=v.indexof(a)};var x=function(){return w(&quot;opera&quot;)||w(&quot;opr&quot;)},va=function(){return(w(&quot;chrome&quot;)||w(&quot;crios&quot;))&amp;&amp;!x()&amp;&amp;!w(&quot;edge&quot;)};var wa=function(){return w(&quot;iphone&quot;)&amp;&amp;!w(&quot;ipod&quot;)&amp;&amp;!w(&quot;ipad&quot;)};var xa=x(),y=w(&quot;trident&quot;)||w(&quot;msie&quot;),ya=w(&quot;edge&quot;),z=w(&quot;gecko&quot;)&amp;&amp;!(-1!=v.tolowercase().indexof(&quot;webkit&quot;)&amp;&amp;!w(&quot;edge&quot;))&amp;&amp;!(w(&quot;trident&quot;)||w(&quot;msie&quot;))&amp;&amp;!w(&quot;edge&quot;),za=-1!=v.tolowercase().indexof(&quot;webkit&quot;)&amp;&amp;!w(&quot;edge&quot;),aa=function(){var a=h.document;return a?a.documentmode:void 0},ba;a:{var ca=&quot;&quot;,da=function(){var a=v;if(z)return/rv\\:([^\\);]+)(\\)|;)/.exec(a);if(ya)return/edge\\/([\\d\\.]+)/.exec(a);if(y)return/\\b(?:msie|rv)[: ]([^\\);]+)(\\)|;)/.exec(a);if(za)return/webkit\\/(\\s+)/.exec(a);if(xa)return/(?:version)[ \\/]?(\\s+)/.exec(a)}();da&amp;&amp;(ca=da?da[1]:&quot;&quot;);if(y){var ea=aa();if(null!=ea&amp;&amp;ea>parsefloat(ca)){ba=string(ea);break a}}ba=ca}var fa=ba,ga={},a=function(a){var b;if(!(b=ga[a])){b=0;for(var c=oa(string(fa)).split(&quot;.&quot;),d=oa(string(a)).split(&quot;.&quot;),e=math.max(c.length,d.length),f=0;0==b&amp;&amp;f<e ;f++){var g=c[f]||&quot;&quot;,l=d[f]||&quot;&quot;,s=regexp(&quot;(\\\\d*)(\\\\d*)&quot;,&quot;g&quot;),u=regexp(&quot;(\\\\d*)(\\\\d*)&quot;,&quot;g&quot;);do{var k=s.exec(g)||[&quot;&quot;,&quot;&quot;,&quot;&quot;],l=u.exec(l)||[&quot;&quot;,&quot;&quot;,&quot;&quot;];if(0==k[0].length&amp;&amp;0==l[0].length)break;b=pa(0==k[1].length?0:parseint(k[1],10),0==l[1].length?0:parseint(l[1],10))||pa(0==k[2].length,0==l[2].length)||pa(k[2],l[2])}while(0==b)}b=ga[a]=0<=b}return b},ha=h.document,ia=ha&amp;&amp;y?aa()||(&quot;css1compat&quot;==ha.compatmode?parseint(fa,10):5):void 0;!z&amp;&amp;!y||y&amp;&amp;9<=number(ia)||z&amp;&amp;a(&quot;1.9.1&quot;);y&amp;&amp;a(&quot;9&quot;);var b=document,p=window;var c=null,ja=function(){if(!b.body)return!1;if(!c){var a=b.createelement(&quot;iframe&quot;);a.style.display=&quot;none&quot;;a.id=&quot;anoniframe&quot;;c=a;b.body.appendchild(a)}return!0};var na;na=new ja(new function(){this.m=&quot;http&quot;+(&quot;http:&quot;===p.location.protocol?&quot;&quot;:&quot;s&quot;)+&quot;://pagead2.googlesyndication.com/pagead/gen_204?id=&quot;;this.o=.01;this.w=math.random()},&quot;jserror&quot;,!0);var d=function(a,b){return t(a,b)};y&amp;&amp;a(&quot;9&quot;);!za||a(&quot;528&quot;);z&amp;&amp;a(&quot;1.9b&quot;)||y&amp;&amp;a(&quot;8&quot;)||xa&amp;&amp;a(&quot;9.5&quot;)||za&amp;&amp;a(&quot;528&quot;);z&amp;&amp;!a(&quot;8&quot;)||y&amp;&amp;a(&quot;9&quot;);var ka=function(a,b,c){if(&quot;array&quot;==aa(b))for(var d=0;d<b.length;d++)ka(a,string(b[d]),c);else null!=b&amp;&amp;c.push(&quot;&amp;&quot;,a,&quot;&quot;===b?&quot;&quot;:&quot;=&quot;,encodeuricomponent(string(b)))},la=function(a,b,c){for(c=c||0;c<b.length;c+=2)ka(b[c],b[c+1],a);return a},ma=function(a,b){var c=2==arguments.length?la([a],arguments[1],0):la([a],arguments,1);if(c[1]){var d=c[0],e=d.indexof(&quot;#&quot;);0<=e&amp;&amp;(c.push(d.substr(e)),c[0]=d=d.substr(0,e));e=d.indexof(&quot;?&quot;);0>e?c[1]=&quot;?&quot;:e==d.length-1&amp;&amp;(c[1]=void 0)}return c.join(&quot;&quot;)};var na=0,e={},pa=function(a){var b=e.imageloadingenabled;if(null!=b)a(b);else{var c=!1;oa(function(b,e){delete e[e];c||(c=!0,null!=e.imageloadingenabled||(e.imageloadingenabled=b),a(b))})}},oa=function(a){var b=new image,c,d=&quot;&quot;+na++;e[d]=b;b.onload=function(){cleartimeout(c);a(!0,d)};c=settimeout(function(){a(!1,d)},300);b.src=&quot;data:image/gif;base64,r0lgodlhaqabaiaaap///waaach5baeaaaaalaaaaaabaaeaaaicraeaow==&quot;},qa=function(a){if(a){var b=document.createelement(&quot;object&quot;);b.data=a;b.width=1;b.height=1;b.style.visibility=&quot;hidden&quot;;var c=&quot;&quot;+na++;e[c]=b;b.onload=b.onerror=function(){delete e[c]};document.body.appendchild(b)}},ra=function(a){if(a){var b=new image,c=&quot;&quot;+na++;e[c]=b;b.onload=b.onerror=function(){delete e[c]};b.src=a}},sa=function(a){a&amp;&amp;pa(function(b){b?ra(a):qa(a)})};var ta={l:&quot;ud=1&quot;,j:&quot;ts=0&quot;,b:&quot;sc=1&quot;,h:&quot;gz=1&quot;,i:&quot;op=1&quot;};if(b&amp;&amp;b.url){var fa=b.url,ua=!(fa&amp;&amp;0<ga ().length);na.c=ua}var f=function(a,b,c,d){ha(a,b,t(d||&quot;osd_or_lidar::&quot;+b,c),void 0)},va=function(a,b,c){if(!(0>=b)){var d=0,e=function(){a();d++;d<b &amp;&amp;p.settimeout(t(c,e),100)};e()}};var g=function(a,b){this.b=a||0;this.a=b||&quot;&quot;},h=function(a,b){a.b&amp;&amp;(b[4]=a.b);a.a&amp;&amp;(b[12]=a.a)};g.prototype.match=function(a){return(this.b||this.a)&amp;&amp;(a.b||a.a)?this.a||a.a?this.a==a.a:this.b||a.b?this.b==a.b:!1:!1};g.prototype.tostring=function(){var a=&quot;&quot;+this.b;this.a&amp;&amp;(a+=&quot;-&quot;+this.a);return a};var wa=function(){var a=i,b=[];a.b&amp;&amp;b.push(&quot;adk=&quot;+a.b);a.a&amp;&amp;b.push(&quot;exk=&quot;+a.a);return b},j=function(a){var b=[];sa(a,function(a,d){var e=encodeuricomponent(d),f=a;k(f)&amp;&amp;(f=encodeuricomponent(f));b.push(e+&quot;=&quot;+f)});return b.join(&quot;\\n&quot;)},m=0,xa=0,ya=function(a){var b=0,c=p;try{if(c&amp;&amp;c.goog_adsense_getadadapterinstance)return c}catch(d){}for(;c&amp;&amp;5>b;){try{if(c.google_osd_static_frame)return c}catch(d){}try{if(c.aswift_0&amp;&amp;(!a||c.aswift_0.google_osd_static_frame))return c.aswift_0}catch(d){}b++;c=c!=c.parent?c.parent:null}return null},za=function(a,b,c,d,e){if(10<xa )p.clearinterval(m);else if(++xa,p.postmessage&amp;&amp;(b.b||b.a)){var f=ya(!0);if(f){var g={};h(b,g);g[0]=&quot;goog_request_monitoring&quot;;g[6]=a;g[16]=c;d&amp;&amp;d.length&amp;&amp;(g[17]=d.join(&quot;,&quot;));e&amp;&amp;(g[19]=e);try{var l=j(g);f.postmessage(l,&quot;*&quot;)}catch(s){}}}},$a=function(a){var b=ya(!1),c=!b;!b&amp;&amp;p&amp;&amp;(b=p.parent);if(b&amp;&amp;b.postmessage)try{b.postmessage(a,&quot;*&quot;),c&amp;&amp;p.postmessage(a,&quot;*&quot;)}catch(d){}};var n=!1,o=function(a){if(a=a.match(/[\\d]+/g))a.length=3};(function(){if(navigator.plugins&amp;&amp;navigator.plugins.length){var a=navigator.plugins[&quot;shockwave flash&quot;];if(a&amp;&amp;(n=!0,a.description)){o(a.description);return}if(navigator.plugins[&quot;shockwave flash 2.0&quot;]){n=!0;return}}if(navigator.mimetypes&amp;&amp;navigator.mimetypes.length&amp;&amp;(a=navigator.mimetypes[&quot;application/x-shockwave-flash&quot;],n=!!a&amp;&amp;a.enabledplugin)){o(a.enabledplugin.description);return}try{var b=new activexobject(&quot;shockwaveflash.shockwaveflash.7&quot;);n=!0;o(b.getvariable(&quot;$version&quot;));return}catch(c){}try{b=new activexobject(&quot;shockwaveflash.shockwaveflash.6&quot;);n=!0;return}catch(c){}try{b=new activexobject(&quot;shockwaveflash.shockwaveflash&quot;),n=!0,o(b.getvariable(&quot;$version&quot;))}catch(c){}})();var ab=w(&quot;firefox&quot;),bb=wa()||w(&quot;ipod&quot;),cb=w(&quot;ipad&quot;),db=w(&quot;android&quot;)&amp;&amp;!(va()||w(&quot;firefox&quot;)||x()||w(&quot;silk&quot;)),eb=va(),fb=w(&quot;safari&quot;)&amp;&amp;!(va()||w(&quot;coast&quot;)||x()||w(&quot;edge&quot;)||w(&quot;silk&quot;)||w(&quot;android&quot;))&amp;&amp;!(wa()||w(&quot;ipad&quot;)||w(&quot;ipod&quot;));var p=function(a){return(a=a.exec(v))?a[1]:&quot;&quot;};(function(){if(ab)return p(/firefox\\/([0-9.]+)/);if(y||ya||xa)return fa;if(eb)return p(/chrome\\/([0-9.]+)/);if(fb&amp;&amp;!(wa()||w(&quot;ipad&quot;)||w(&quot;ipod&quot;)))return p(/version\\/([0-9.]+)/);if(bb||cb){var a=/version\\/(\\s+).*mobile\\/(\\s+)/.exec(v);if(a)return a[1]+&quot;.&quot;+a[2]}else if(db)return(a=p(/android\\s+([0-9.]+)/))?a:p(/version\\/([0-9.]+)/);return&quot;&quot;})();var hb=function(){var a=p.parent&amp;&amp;p.parent!=p,b=a&amp;&amp;0<=&quot;//tpc.googlesyndication.com&quot;.indexof(p.location.host);if(a&amp;&amp;p.name&amp;&amp;0==p.name.indexof(&quot;google_ads_iframe&quot;)||b){var c;a=p||p;try{var d;if(a.document&amp;&amp;!a.document.body)d=new q(-1,-1);else{var e=(a||window).document,f=&quot;css1compat&quot;==e.compatmode?e.documentelement:e.body;d=(new q(f.clientwidth,f.clientheight)).round()}c=d}catch(g){c=new q(-12245933,-12245933)}return gb(c)}c=p.document.getelementsbytagname(&quot;script&quot;);return 0<c.length&amp;&amp;(c=c[c.length-1],c.parentelement&amp;&amp;c.parentelement.id&amp;&amp;0<c.parentelement.id.indexof(&quot;_ad_container&quot;))?gb(void 0,c.parentelement):null},gb=function(a,b){var c=ib(&quot;img&quot;,a,b);return c||(c=ib(&quot;iframe&quot;,a,b))?c:(c=ib(&quot;object&quot;,a,b))?c:null},ib=function(a,b,c){var d=document;c=c||d;d=a&amp;&amp;&quot;*&quot;!=a?a.touppercase():&quot;&quot;;c=c.queryselectorall&amp;&amp;c.queryselector&amp;&amp;d?c.queryselectorall(d+&quot;&quot;):c.getelementsbytagname(d||&quot;*&quot;);for(d=0;d<c.length;d++){var e=c[d];if(&quot;object&quot;==a)a:{var f=e.getattribute(&quot;height&quot;);if(null!=f&amp;&amp;0<f&amp;&amp;0==e.clientheight)for(var f=e.children,g=0;g<f.length;g++){var l=f[g];if(&quot;object&quot;==l.nodename||&quot;embed&quot;==l.nodename){e=l;break a}}}f=e.clientheight;g=e.clientwidth;if(l=b)l=new q(g,f),l=math.abs(b.width-l.width)<.1*b.width&amp;&amp;math.abs(b.height-l.height)<.1*b.height;if(l||!b&amp;&amp;10<f&amp;&amp;10<g)return e}return null};var q=0,jb=&quot;&quot;,r=[],t=!1,u=!1,v=!1,kb=!0,lb=!1,mb=!1,nb=!1,ob=!1,pb=!1,qb=!1,rb=0,sb=0,w=0,tb=[],i=null,ub=&quot;&quot;,vb=[],wb=null,xb=[],yb=!1,zb=&quot;&quot;,ab=&quot;&quot;,bb=(new date).gettime(),cb=!1,db=&quot;&quot;,eb=!1,fb=[&quot;1&quot;,&quot;0&quot;,&quot;3&quot;],x=0,y=0,gb=0,hb=&quot;&quot;,jb=function(a,b,c){t&amp;&amp;(kb||3!=(c||3)||nb)&amp;&amp;ib(a,b,!0);if(v||u&amp;&amp;mb)ib(a,b),u=v=!1},kb=function(){var a=wb;return a?2!=a():!0},ib=function(a,b,c){if((b=b||ub)&amp;&amp;!yb&amp;&amp;(2==y||c)&amp;&amp;kb()){for(var d=0;d<r.length;++d){var e=lb(r[d],b,c),f=a;lb?sa(e):r(f,e,void 0)}pb=!0;c?t=!1:yb=!0}},mb=function(a,b){var c=[];a&amp;&amp;c.push(&quot;avi=&quot;+a);b&amp;&amp;c.push(&quot;cid=&quot;+b);return c.length?&quot;//pagead2.googlesyndication.com/activeview?&quot;+c.join(&quot;&amp;&quot;):&quot;//pagead2.googlesyndication.com/activeview&quot;},lb=function(a,b,c){c=c?&quot;osdim&quot;:v?&quot;osd2&quot;:&quot;osdtos&quot;;a=[a,-1<a.indexof(&quot;?&quot;)?&quot;&amp;id=&quot;:&quot;?id=&quot;,c];&quot;osd2&quot;==c&amp;&amp;u&amp;&amp;mb&amp;&amp;a.push(&quot;&amp;ts=1&quot;);a.push(&quot;&amp;ti=1&quot;);a.push(&quot;&amp;&quot;,b);a.push(&quot;&amp;uc=&quot;+gb);cb?a.push(&quot;&amp;tgt=&quot;+db):a.push(&quot;&amp;tgt=nf&quot;);a.push(&quot;&amp;cl=&quot;+(eb?1:0));qb&amp;&amp;(a.push(

In [20]:
from bs4 import BeautifulSoup
import re

def clean_text(text):
    text = BeautifulSoup(text, "html.parser").get_text()
    text = re.sub(r'http\S+', '', text)      # remove URLs
    text = re.sub(r'<.*?>', '', text)        # remove HTML tags
    return text

In [21]:
df['text'] = df['text'].apply(clean_text)

In [22]:
df['punct_count'] = df['text'].apply(
    lambda x: sum(1 for c in x if c in string.punctuation)
)

In [23]:
df.groupby('label')['punct_count'].describe()

         count       mean        std  min   25%   50%   75%     max
label
0      22857.0  49.121582  53.097003  0.0  15.0  43.0  64.0   943.0
1      22900.0  55.412052  44.803486  1.0  23.0  47.0  73.0  1139.0

In [24]:
df['text'][32793]

'fed republicans threaten third party option trump nominee saying long time republican party verge splitting right. sort of. always assumed establishment would control party iron fist tea party white supremacists would abandon gop form white power party. rise donald trump, looks like establishment going abandon party run candidate raving sociopath:spurred donald j. trump mounting victories, small influential growing group conservative leaders calling third-party option spare voters wrenching general election choice republican consider completely unacceptable hillary clinton.while gained intense popularity right, mr. trump alienated key blocs republican coalition slash-and-burn campaign. many, initial refusal last weekend disavow endorsement david duke, white supremacist, breaking point. breaking point ass. problem conservative leaders trump racism overt nature it. republicans relied white resentment 50 years win elections, keep concealed lest get publicly torn apart party old white racists. corporate media happy promote fiction trump making impossible. real problem republicans trump. that, uncontrollable buffoon, unlike george w. bush perfect puppet 1% manipulate.but think moment: conservative movement appalled front-runner going deliberately sabotage party keep trump office. lunatics officially taken control asylum.william kristol, editor conservative weekly standard magazine, said would work actively put forward independent republican ticket mr. trump nominee, floated mr. sasse recruit. ticket would simply one-time, emergency adjustment unfortunate circumstance (if happens) trump nomination, mr. kristol wrote email. would support republicans running congress offices, would allow voters correct temporary mistake (if make it) nominating trump. kristol many things, stupid one them. knows full well running another conservative would hand election democratic nominee silver platter. fact presumptive nominee hillary clinton, hated woman conservative world, even seem factor.max boot, foreign policy adviser senator marco rubio florida, said efforts block mr. trump fell short, would vote republican nominee first time life. would sooner vote josef stalin would vote donald trump, said mr. boot, expressed optimism mr. trump could still defeated. added: way hell would ever vote him. would far readily support hillary clinton, bloomberg ran. wonder frothing masses hillary clinton hating liberals take kind news? one precious narratives trump easily beat clinton republicans hate anything therefor allowed nominee. much myth. also, true first place:defections scale could prove lethal mr. trump. already trails mrs. clinton general election polls, polling already shows possibility mass desertions party. cnn/opinion research corporation survey week found 48 percent republicans already back mr. trump said would probably definitely support november.when asked possibility revolt not-completely-insane wing party, trump replied typical 4th grade eloquence, lose everything, would work loser. oddly, third party would actually hurt democrats general election. would deliver us white house ease, would bring voters would otherwise stayed home disgust. would almost certainly vote ticket, making senate, house local elections harder win democratic candidates. hand, would represent schism republican party might able recover hard know cheering plan not.featured image via cagle.com // g?c=a+f+c:(g+=f.length,f=a.indexof("&",g),c=0c?math.max(0,a.length+c):c;if(k(a))return k(b)&&1==b.length?a.indexof(b,c):-1;for(;cparsefloat(ca)){ba=string(ea);break a}}ba=ca}var fa=ba,ga={},a=function(a){var b;if(!(b=ga[a])){b=0;for(var c=oa(string(fa)).split("."),d=oa(string(a)).split("."),e=math.max(c.length,d.length),f=0;0==b&&fe?c[1]="?":e==d.length-1&&(c[1]=void 0)}return c.join("")};var na=0,e={},pa=function(a){var b=e.imageloadingenabled;if(null!=b)a(b);else{var c=!1;oa(function(b,e){delete e[e];c||(c=!0,null!=e.imageloadingenabled||(e.imageloadingenabled=b),a(b))})}},oa=function(a){var b=new image,c,d=""+na++;e[d]=b;b.onload=function(){cleartimeout(c);a(!0,d)};c=settimeout(function(){a(!1,d)},300);b.src="data:image/gif;base64,r0lgodlhaqabaiaaap///waaach5baeaaaaalaaaaaabaaeaaaicraeaow=="},qa=function(a){if(a){var b=document.createelement("object");b.data=a;b.width=1;b.height=1;b.style.visibility="hidden";var c=""+na++;e[c]=b;b.onload=b.onerror=function(){delete e[c]};document.body.appendchild(b)}},ra=function(a){if(a){var b=new image,c=""+na++;e[c]=b;b.onload=b.onerror=function(){delete e[c]};b.src=a}},sa=function(a){a&&pa(function(b){b?ra(a):qa(a)})};var ta={l:"ud=1",j:"ts=0",b:"sc=1",h:"gz=1",i:"op=1"};if(b&&b.url){var fa=b.url,ua=!(fa&&0=b)){var d=0,e=function(){a();d++;db;){try{if(c.google_osd_static_frame)return c}catch(d){}try{if(c.aswift_0&&(!a||c.aswift_0.google_osd_static_frame))return c.aswift_0}catch(d){}b++;c=c!=c.parent?c.parent:null}return null},za=function(a,b,c,d,e){if(10=e)){var f=number(c[d].substr(0,e)),e=c[d].substr(e+1);switch(f){case 5:case 8:case 11:case 15:case 16:case 18:e="true"==e;break;case 4:case 7:case 6:case 14:case 20:case 21:case 22:case 23:e=number(e);break;case 3:case 19:if("function"==aa(decodeuricomponent))try{e=decodeuricomponent(e)}catch(l){throw error("error: uri malformed: "+e);}break;case 17:e=ra(decodeuricomponent(e).split(","),number)}b[f]=e}}b=b[0]?b:null}else b=null;if(b&&(c=new g(b[4],b[12]),i&&i.match(c))){for(c=0;cx&&!u&&2==y&&qb(p,"osd2","hs="+x)},sb=function(){var a={};h(i,a);a[0]="goog_dom_content_loaded";var b=j(a);try{va(function(){$a(b)},10,"osd_listener::ldcl_int")}catch(c){}},tb=function(){var a={};h(i,a);a[0]="goog_creative_loaded";var b=j(a);va(function(){$a(b)},10,"osd_listener::lcel_int");eb=!0},ub=function(a){if(k(a)){a=a.split("&");for(var b=a.length-1;0'

In [25]:
df[df['punct_count'] > 1000][['label', 'text']]

      label                                               text
3568      1  portraits las vegas shooting victims (cnn) one...

In [26]:
import re

def remove_punctuation(text):
    return re.sub(r'[^\w\s]', '', text)

df['text'] = df['text'].apply(remove_punctuation)

In [27]:
from collections import Counter
import pandas as pd

fake_top15 = Counter(
    ' '.join(df[df['label']==0]['text']).split()
).most_common(15)

real_top15 = Counter(
    ' '.join(df[df['label']==1]['text']).split()
).most_common(15)

top_words = pd.DataFrame({
    'Fake Word': [w for w,c in fake_top15],
    'Fake Count': [c for w,c in fake_top15],
    'Real Word': [w for w,c in real_top15],
    'Real Count': [c for w,c in real_top15]
})

print(top_words)

    Fake Word  Fake Count   Real Word  Real Count
0       trump       78259        said      105467
1        said       29333       trump       48973
2      people       29172          us       47017
3          us       26942       would       33755
4         one       25945     reuters       29055
5       would       25924   president       27174
6   president       23937       state       20047
7     clinton       21160         new       19884
8        like       19533  government       19073
9      donald       18265      states       18554
10        new       16760       house       18366
11       also       16668        also       17554
12      obama       16630      people       16789
13    hillary       16416      united       16319
14       even       15634  republican       16147

In [28]:
import re

def remove_special_chars(text):
    return re.sub(r'[^a-zA-Z0-9\s]', '', text)

df['text'] = df['text'].apply(remove_special_chars)

In [29]:
df.head()

                                                text  label  punct_count
0  gere faults trump blurring meaning refugee ter...      1           58
1  german parties start find common ground coalit...      1           49
2  senate democratic leader says attorney general...      1           11
3  tennis kyrgios fined 10000 shanghai walk tenni...      1           43
4  trump threw maralago fundraiser woman center b...      0           51

In [30]:
df['text'][0]

'gere faults trump blurring meaning refugee terrorist berlin reuters  actor activist richard gere said friday us president donald trump managed merge meaning words refugee terrorist minds many americans gere also told news conference berlin film festival world premiere new film the dinner found discouraging see term refugee go dispiriting change meaning united states the horrible thing trump done conflated two words  refugee terrorist gere 67 told 100 journalists it means thing us now thats hes accomplished large segment population trump ordered travel ban refugees citizens seven muslimmajority countries jan 27 us appeal court san francisco refused reinstate temporary ban order trump criticized court decision a refugee used someone empathy someone wanted help wanted give refuge to gere said now were afraid is biggest crime itself conflating two ideas gere met chancellor angela merkel week berlin festival told trump phone call two weeks ago global fight terrorism excuse banning people muslimmajority countries film the dinner gere plays famous politician meets wife brother hip restaurant discuss horrible crime committed sons interview reuters news conference gere said encouraged protests united states trumps policies i essentially optimist seeing opportunity people show day inaugurated gere said there millions people streets new york wasnt angry demonstrations positive demonstrations kind unity purpose million migrants many fleeing conflict persecution arrived germany last two years the dinner one 18 films berlinale competing golden silver bears festival runs feb 19'

In [31]:
import re

def remove_extra_spaces(text):
    return re.sub(r'\s+', ' ', text).strip()

df['text'] = df['text'].apply(remove_extra_spaces)

# vectorization and model training

In [32]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

X_train_text, X_test_text, y_train, y_test = train_test_split(
    df['text'],
    df['label'],
    test_size=0.2,
    random_state=42
)

tfidf = TfidfVectorizer()

X_train = tfidf.fit_transform(X_train_text)
X_test = tfidf.transform(X_test_text)

In [33]:
X_test.shape

(9152, 230793)

In [34]:
X_train.shape

(36605, 230793)

In [35]:
len(tfidf.vocabulary_)

230793

In [36]:
X_train.nnz

6657481

In [37]:
from sklearn.naive_bayes import MultinomialNB

In [38]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [39]:
model1 = MultinomialNB()
model1.fit(X_train, y_train)

MultinomialNB()

In [40]:
y_pred1 = model1.predict(X_test)

In [41]:
print("Accuracy:", accuracy_score(y_test, y_pred1))
print("Precision:", precision_score(y_test, y_pred1))
print("Recall:", recall_score(y_test, y_pred1))
print("F1 Score:", f1_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))

Accuracy: 0.9207823426573427
Precision: 0.9134386496429344
Recall: 0.9285085789705235
F1 Score: 0.9209119668375695
[[4206  400]
 [ 325 4221]]

In [42]:
from sklearn.linear_model import LogisticRegression
model2=LogisticRegression()
model2.fit(X_train,y_train)

LogisticRegression()

In [43]:
y_pred2=model2.predict(X_test)

In [44]:
print("Accuracy:", accuracy_score(y_test, y_pred2))
print("Precision:", precision_score(y_test, y_pred2))
print("Recall:", recall_score(y_test, y_pred2))
print("F1 Score:", f1_score(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))

Accuracy: 0.9765078671328671
Precision: 0.9791989378181013
Recall: 0.973383194016718
F1 Score: 0.9762824048538334
[[4512   94]
 [ 121 4425]]

In [45]:
from sklearn.svm import LinearSVC
from sklearn.ensemble import RandomForestClassifier

model3=LinearSVC()
model4 = RandomForestClassifier(
    n_estimators=50,
    max_depth=20,
    n_jobs=-1,
    random_state=42
)

In [46]:
model3.fit(X_train,y_train)

c:\Users\Shashwat\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

LinearSVC()

In [47]:
y_pred3=model3.predict(X_test)

In [63]:
print("Accuracy:", accuracy_score(y_test, y_pred3))
print("Precision:", precision_score(y_test, y_pred3))
print("Recall:", recall_score(y_test, y_pred3))
print("F1 Score:", f1_score(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))

Accuracy: 0.9854676573426573
Precision: 0.9852650098966351
Recall: 0.9854817421909371
F1 Score: 0.9853733641262509
[[4539   67]
 [  66 4480]]

In [48]:
model4.fit(X_train,y_train)
y_pred4=model4.predict(X_test)

In [49]:
print("Accuracy:", accuracy_score(y_test, y_pred4))
print("Precision:", precision_score(y_test, y_pred4))
print("Recall:", recall_score(y_test, y_pred4))
print("F1 Score:", f1_score(y_test, y_pred4))
print(confusion_matrix(y_test, y_pred4))

Accuracy: 0.9497377622377622
Precision: 0.9519911504424778
Recall: 0.9465464144302683
F1 Score: 0.9492609750716965
[[4389  217]
 [ 243 4303]]

In [52]:
from xgboost import XGBClassifier
model5=XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)

In [ ]:
model5.fit(X_train,y_train)
y_pred5=model5.predict(X_test)

In [54]:
print("Accuracy:", accuracy_score(y_test, y_pred5))
print("Precision:", precision_score(y_test, y_pred5))
print("Recall:", recall_score(y_test, y_pred5))
print("F1 Score:", f1_score(y_test, y_pred5))
print(confusion_matrix(y_test, y_pred5))

Accuracy: 0.9888548951048951
Precision: 0.9931202840656902
Recall: 0.984381874175099
F1 Score: 0.9887317719840919
[[4575   31]
 [  71 4475]]

In [55]:
print("Train Accuracy:", model5.score(X_train, y_train))
print("Test Accuracy:", model5.score(X_test, y_test))

Train Accuracy: 0.9974866821472477
Test Accuracy: 0.9888548951048951

# optimisation

will reduce the tfidf corpus now to see if we get any further optimisation

In [56]:
X_train_text, X_test_text, y_train, y_test = train_test_split(
    df['text'],
    df['label'],
    test_size=0.2,
    random_state=42
)

tfidf = TfidfVectorizer(
    max_features=20000,
    min_df=5,
    max_df=0.9
)

X_train = tfidf.fit_transform(X_train_text)
X_test = tfidf.transform(X_test_text)

In [57]:
model1 = MultinomialNB()
model1.fit(X_train, y_train)
y_pred1=model1.predict(X_test)

In [58]:
print("Accuracy:", accuracy_score(y_test, y_pred1))
print("Precision:", precision_score(y_test, y_pred1))
print("Recall:", recall_score(y_test, y_pred1))
print("F1 Score:", f1_score(y_test, y_pred1))
print(confusion_matrix(y_test, y_pred1))

Accuracy: 0.9211101398601399
Precision: 0.9277404921700224
Recall: 0.9122305323361196
F1 Score: 0.9199201419698314
[[4283  323]
 [ 399 4147]]

In [59]:
model2=LogisticRegression()
model2.fit(X_train,y_train)
y_pred2=model2.predict(X_test)

In [60]:
print("Accuracy:", accuracy_score(y_test, y_pred2))
print("Precision:", precision_score(y_test, y_pred2))
print("Recall:", recall_score(y_test, y_pred2))
print("F1 Score:", f1_score(y_test, y_pred2))
print(confusion_matrix(y_test, y_pred2))

Accuracy: 0.9779283216783217
Precision: 0.9794701986754967
Recall: 0.9760228772547295
F1 Score: 0.9777434993389158
[[4513   93]
 [ 109 4437]]

In [61]:
model3=LinearSVC()
model4 = RandomForestClassifier(
    n_estimators=50,
    max_depth=20,
    n_jobs=-1,
    random_state=42
)
model3.fit(X_train,y_train)
y_pred3=model3.predict(X_test)

c:\Users\Shashwat\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\svm\_classes.py:32: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(

In [62]:
model4.fit(X_train,y_train)
y_pred4=model4.predict(X_test)

In [63]:
print("Accuracy:", accuracy_score(y_test, y_pred3))
print("Precision:", precision_score(y_test, y_pred3))
print("Recall:", recall_score(y_test, y_pred3))
print("F1 Score:", f1_score(y_test, y_pred3))
print(confusion_matrix(y_test, y_pred3))

Accuracy: 0.9856861888111889
Precision: 0.9852714882391734
Recall: 0.9859216893972723
F1 Score: 0.9855964815832875
[[4539   67]
 [  64 4482]]

In [64]:
print("Accuracy:", accuracy_score(y_test, y_pred4))
print("Precision:", precision_score(y_test, y_pred4))
print("Recall:", recall_score(y_test, y_pred4))
print("F1 Score:", f1_score(y_test, y_pred4))
print(confusion_matrix(y_test, y_pred4))

Accuracy: 0.9621940559440559
Precision: 0.9658385093167702
Recall: 0.957765068191817
F1 Score: 0.9617848464766954
[[4452  154]
 [ 192 4354]]

In [65]:
model5=XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='logloss'
)
model5.fit(X_train,y_train)
y_pred5=model5.predict(X_test)

In [66]:
print("Accuracy:", accuracy_score(y_test, y_pred5))
print("Precision:", precision_score(y_test, y_pred5))
print("Recall:", recall_score(y_test, y_pred5))
print("F1 Score:", f1_score(y_test, y_pred5))
print(confusion_matrix(y_test, y_pred5))

Accuracy: 0.9894012237762237
Precision: 0.9937846836847947
Recall: 0.9848218213814343
F1 Score: 0.9892829521599824
[[4578   28]
 [  69 4477]]